'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Logic.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Accept.
        '''</summary>
        Friend Shared ReadOnly Property BtnAcceptPet_M_P() As String
            Get
                Return ResourceManager.GetString("BtnAcceptPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ADD PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify pathology.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HPP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Admins.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_H() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Admins.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BACK.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BACK.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Patient1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Patient1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CANCELL.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancelPetition_P_HD() As String
            Get
                Return ResourceManager.GetString("BtnCancelPetition_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REMOVE SYMPTOM.
        '''</summary>
        Friend Shared ReadOnly Property BtnDropPathology_P_H() As String
            Get
                Return ResourceManager.GetString("BtnDropPathology_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FINALIZE.
        '''</summary>
        Friend Shared ReadOnly Property BtnEnd_P_H() As String
            Get
                Return ResourceManager.GetString("BtnEnd_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOGOUT.
        '''</summary>
        Friend Shared ReadOnly Property BtnExit_A_L() As String
            Get
                Return ResourceManager.GetString("BtnExit_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_H() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home page.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_M_H() As String
            Get
                Return ResourceManager.GetString("BtnHome_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOGIN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_A_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOGIN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_M_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOGIN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_P_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_H() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogOut_M_H() As String
            Get
                Return ResourceManager.GetString("BtnLogOut_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medics.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_H() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medics.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFY PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property BtnModifyPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnModifyPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a START.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Result_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Symptom1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Symptom1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Requests.
        '''</summary>
        Friend Shared ReadOnly Property BtnRequest_M_H() As String
            Get
                Return ResourceManager.GetString("BtnRequest_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REMOVE PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property BtnRmPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnRmPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REQUEST CHAT.
        '''</summary>
        Friend Shared ReadOnly Property BtnSendChatP_P_H() As String
            Get
                Return ResourceManager.GetString("BtnSendChatP_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_H() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The chat has finished!.
        '''</summary>
        Friend Shared ReadOnly Property ChatFinished_P_HC() As String
            Get
                Return ResourceManager.GetString("ChatFinished_P_HC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checking fields..
        '''</summary>
        Friend Shared ReadOnly Property CheckingFields() As String
            Get
                Return ResourceManager.GetString("CheckingFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify Diagnose.
        '''</summary>
        Friend Shared ReadOnly Property ChkModDiag_M_C() As String
            Get
                Return ResourceManager.GetString("ChkModDiag_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wrong Identity Card..
        '''</summary>
        Friend Shared ReadOnly Property CiWrong() As String
            Get
                Return ResourceManager.GetString("CiWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close Chat.
        '''</summary>
        Friend Shared ReadOnly Property CloseChat_M_C() As String
            Get
                Return ResourceManager.GetString("CloseChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close Program.
        '''</summary>
        Friend Shared ReadOnly Property CloseProgram_M_H() As String
            Get
                Return ResourceManager.GetString("CloseProgram_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connection failed. Trying to recover data....
        '''</summary>
        Friend Shared ReadOnly Property ConnectionFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Successfully modified diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property DiagnosticModSuccess_M_C() As String
            Get
                Return ResourceManager.GetString("DiagnosticModSuccess_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to end the chat?.
        '''</summary>
        Friend Shared ReadOnly Property EndChat_M_C() As String
            Get
                Return ResourceManager.GetString("EndChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is an empty field..
        '''</summary>
        Friend Shared ReadOnly Property HayCamposVacios() As String
            Get
                Return ResourceManager.GetString("HayCamposVacios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agustín Yorel Acosta Bergonzoni..
        '''</summary>
        Friend Shared ReadOnly Property Label13() As String
            Get
                Return ResourceManager.GetString("Label13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Kevin Mathew Anadón Wappler..
        '''</summary>
        Friend Shared ReadOnly Property Label14() As String
            Get
                Return ResourceManager.GetString("Label14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mayza Daniela Ferreira Hernández..
        '''</summary>
        Friend Shared ReadOnly Property Label15() As String
            Get
                Return ResourceManager.GetString("Label15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignacio Rodríguez Sosa..
        '''</summary>
        Friend Shared ReadOnly Property Label16() As String
            Get
                Return ResourceManager.GetString("Label16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Introduction.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_Intro_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl1_Intro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patient.
        '''</summary>
        Friend Shared ReadOnly Property Lbl2_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl2_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property Lbl3_Symptom_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl3_Symptom_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Results.
        '''</summary>
        Friend Shared ReadOnly Property Lbl4_Result_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl4_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property Lbl5_Chat_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl5_Chat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter your username and password
        '''to authenticate and verify your credentials.
        '''This Software will allow you to treat your Patients, providing them with information to conclude a Tele Diagnosis..
        '''</summary>
        Friend Shared ReadOnly Property LblBody_M_L() As String
            Get
                Return ResourceManager.GetString("LblBody_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a If you wish, you can consult a doctor..
        '''</summary>
        Friend Shared ReadOnly Property LblChat_P_H() As String
            Get
                Return ResourceManager.GetString("LblChat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Health Care Center.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Required field.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generating connection with the Database..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generating connection with the Database..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_P_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_P_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You are about to perform a brief (3 min), safe and anonymous medical check-up. Your answers will be carefully analyzed and you will be told the possible causes of your safe symptoms. The information you provide is anonymous and will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Before using this tool, please read the terms of service.
        '''
        '''Remember that:
        '''The checkup is for informational purposes and is not a substitute for a doctor&apos;s opinion.
        '''Do not use in an emergency. In the event of a health emergency, call your local emergency number immediately. Your data is safe. The information you provide is anonymous and will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Management System for Administrators..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Management treatments.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This Medical System was created with the purpose of fulfilling the expectations of an Assistant Program, which will guide you throughout your diagnosis of pathologies that you may suffer. As this is an Assistant, you will be able to know your Pathologies in the most agile and simple way.
        '''
        '''Enjoy our service. Tap the button below to start the anonymous diagnosis and it will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a V2.0.1 Beta..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo3_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo3_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a © Telediagnóstico Médico 2020. All rights reserved..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo4_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a END.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoEnd_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoEnd_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DIAGNOSED PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoPathSuffered_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoPathSuffered_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATIENT.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoPatient_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoPatient_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SUFFERED SYMPTOMS.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoSympsSuffered_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoSympsSuffered_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter your username and password to authenticate and verify your credentials. This Software will allow you to manage the Staff, the Medics, the Patients, the Symptoms and their associated Pathologies..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_A_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter your Identity Card to authenticate and verify your credentials. This Software will allow you to make Primary Diagnoses and based on them you will decide if you want to start a conversation with a Medical Specialist..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_P_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LIST OF REQUESTS.
        '''</summary>
        Friend Shared ReadOnly Property LblListadoPet_M_P() As String
            Get
                Return ResourceManager.GetString("LblListadoPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medic.
        '''</summary>
        Friend Shared ReadOnly Property LblMedic_P_HC() As String
            Get
                Return ResourceManager.GetString("LblMedic_P_HC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MANAGEMENT PATHOLOGIES.
        '''</summary>
        Friend Shared ReadOnly Property LblMgmentPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblMgmentPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFY DIAGNOSE.
        '''</summary>
        Friend Shared ReadOnly Property LblModDiagnostic_M_C() As String
            Get
                Return ResourceManager.GetString("LblModDiagnostic_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology.
        '''</summary>
        Friend Shared ReadOnly Property LblModDiagPath_M_C() As String
            Get
                Return ResourceManager.GetString("LblModDiagPath_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patient.
        '''</summary>
        Friend Shared ReadOnly Property LblPatientChat_M_C() As String
            Get
                Return ResourceManager.GetString("LblPatientChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REQUESTED PETITIONS.
        '''</summary>
        Friend Shared ReadOnly Property LblPet_M_P() As String
            Get
                Return ResourceManager.GetString("LblPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GENERATING REQUEST.
        '''</summary>
        Friend Shared ReadOnly Property LblPetitionInfo_P_H() As String
            Get
                Return ResourceManager.GetString("LblPetitionInfo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please note that the list may not be complete and that the information provided is for informational purposes and does not reflect an actual medical opinion..
        '''</summary>
        Friend Shared ReadOnly Property LblResultInfoo_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultInfoo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LIST OF PATHOLOGIES.
        '''</summary>
        Friend Shared ReadOnly Property LblResultPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblResultPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Results.
        '''</summary>
        Friend Shared ReadOnly Property LblResults_P_H() As String
            Get
                Return ResourceManager.GetString("LblResults_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATHOLOGIES SUFFERED.
        '''</summary>
        Friend Shared ReadOnly Property LblResultsTitle_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultsTitle_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a It does not require an urgent medical evaluation..
        '''</summary>
        Friend Shared ReadOnly Property LblResultUrgent_M_C_NOTURGENTE() As String
            Get
                Return ResourceManager.GetString("LblResultUrgent_M_C_NOTURGENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a It requires an urgent medical evaluation..
        '''</summary>
        Friend Shared ReadOnly Property LblResultUrgent_M_C_URGENTE() As String
            Get
                Return ResourceManager.GetString("LblResultUrgent_M_C_URGENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEARCH CRITERIA.
        '''</summary>
        Friend Shared ReadOnly Property LblSearch_A_HP() As String
            Get
                Return ResourceManager.GetString("LblSearch_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Owner.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology name.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Choose one answer in each row..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please choose the symptoms from the drop down list..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mortality index.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select an item to delete.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System version.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology description.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System&apos;s developers.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Kind of pathology.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Treatment name.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle5_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle5_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Treatment description.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle6_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle6_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Kind of treatment.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle7_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle7_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LIST OF TREATMENTS FOR PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle8_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle8_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Age.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleAge_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleAge_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last Connection.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleConn_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleConn_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Credential.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleCred_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleCred_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleEmail_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleEmail_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Full Name.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleName_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleName_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number Phone.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleTel_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleTel_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System.
        '''</summary>
        Friend Shared ReadOnly Property LblSystemChat_M_C() As String
            Get
                Return ResourceManager.GetString("LblSystemChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ABOUT SYSTEM.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFY PATHOLOGY.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a WELCOME BACK.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a WELCOME BACK.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please select all statements
        '''that apply to you..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add your symptoms to the list..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ABOUT ADMINISTRATOR.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  .
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ABOUT MEDIC.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_M_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a    .
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms you suffer from..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hello!.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a License Terms..
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a In a conversation with the Doctor:.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleNameMedic_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleNameMedic_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  .
        '''</summary>
        Friend Shared ReadOnly Property LblTittle1_M_L() As String
            Get
                Return ResourceManager.GetString("LblTittle1_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a WELCOME BACK.
        '''</summary>
        Friend Shared ReadOnly Property LblTittle2_M_L() As String
            Get
                Return ResourceManager.GetString("LblTittle2_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a In a conversation with the Patient:.
        '''</summary>
        Friend Shared ReadOnly Property LblTittleChat_M_C() As String
            Get
                Return ResourceManager.GetString("LblTittleChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I am overweight, or I am obese..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt1_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt1_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I smoke cigarettes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt2_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt2_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I have recently suffered an injury..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt3_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt3_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I have high cholesterol..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt4_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt4_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I have hypertension..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt5_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt5_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I have diabetes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt6_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt6_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to log out?.
        '''</summary>
        Friend Shared ReadOnly Property LogOut_M_H() As String
            Get
                Return ResourceManager.GetString("LogOut_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CORRECTLY GENERATED PETITION.
        '''</summary>
        Friend Shared ReadOnly Property MadeRequest_P_HD() As String
            Get
                Return ResourceManager.GetString("MadeRequest_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MAKING REQUEST.
        '''</summary>
        Friend Shared ReadOnly Property MakingRequest_P_HD() As String
            Get
                Return ResourceManager.GetString("MakingRequest_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to exit ?.
        '''</summary>
        Friend Shared ReadOnly Property MsgExit() As String
            Get
                Return ResourceManager.GetString("MsgExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a It is not enabled..
        '''</summary>
        Friend Shared ReadOnly Property NotEnable() As String
            Get
                Return ResourceManager.GetString("NotEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a I don&apos;t know..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Idk_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Idk_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_No_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_No_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yes..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Yes_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Yes_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medicine.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnMedicine_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnMedicine_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Surgical.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnQuir_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnQuir_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Successful Login..
        '''</summary>
        Friend Shared ReadOnly Property SuccessLogin() As String
            Get
                Return ResourceManager.GetString("SuccessLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Make search by pathologies.
        '''</summary>
        Friend Shared ReadOnly Property TxtSearchPath_A_HP() As String
            Get
                Return ResourceManager.GetString("TxtSearchPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User .
        '''</summary>
        Friend Shared ReadOnly Property UserInfoHome_A_H() As String
            Get
                Return ResourceManager.GetString("UserInfoHome_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a connected at .
        '''</summary>
        Friend Shared ReadOnly Property UserInfoHomeCon_A_H() As String
            Get
                Return ResourceManager.GetString("UserInfoHomeCon_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User or Password wrong..
        '''</summary>
        Friend Shared ReadOnly Property UserOrPassWrong() As String
            Get
                Return ResourceManager.GetString("UserOrPassWrong", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
