'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Logic.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BACK.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BACK.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Patient1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Patient1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REMOVE SYMPTOM.
        '''</summary>
        Friend Shared ReadOnly Property BtnDropPathology_P_H() As String
            Get
                Return ResourceManager.GetString("BtnDropPathology_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FINALIZE.
        '''</summary>
        Friend Shared ReadOnly Property BtnEnd_P_H() As String
            Get
                Return ResourceManager.GetString("BtnEnd_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOGIN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_P_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to START.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Result_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NEXT.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Symptom1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Symptom1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REQUEST CHAT.
        '''</summary>
        Friend Shared ReadOnly Property BtnSendChatP_P_H() As String
            Get
                Return ResourceManager.GetString("BtnSendChatP_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introduction.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_Intro_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl1_Intro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient.
        '''</summary>
        Friend Shared ReadOnly Property Lbl2_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl2_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property Lbl3_Symptom_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl3_Symptom_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results.
        '''</summary>
        Friend Shared ReadOnly Property Lbl4_Result_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl4_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat.
        '''</summary>
        Friend Shared ReadOnly Property Lbl5_Chat_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl5_Chat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In future versions of our system, you will be able to consult with a Doctor..
        '''</summary>
        Friend Shared ReadOnly Property LblChat_P_H() As String
            Get
                Return ResourceManager.GetString("LblChat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generating connection with the Database..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_P_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_P_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are about to perform a brief (3 min), safe and anonymous medical check-up. Your answers will be carefully analyzed and you will be told the possible causes of your safe symptoms. The information you provide is anonymous and will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before using this tool, please read the terms of service.
        '''
        '''Remember that:
        '''The checkup is for informational purposes and is not a substitute for a doctor&apos;s opinion.
        '''Do not use in an emergency. In the event of a health emergency, call your local emergency number immediately. Your data is safe. The information you provide is anonymous and will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Medical System was created with the purpose of fulfilling the expectations of an Assistant Program, which will guide you throughout your diagnosis of pathologies that you may suffer. As this is an Assistant, you will be able to know your Pathologies in the most agile and simple way.
        '''
        '''Enjoy our service. Tap the button below to start the anonymous diagnosis and it will not be shared with anyone..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your Identity Card to authenticate and verify your credentials. This Software will allow you to make Primary Diagnoses and based on them you will decide if you want to start a conversation with a Medical Specialist..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_P_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GENERATING REQUEST.
        '''</summary>
        Friend Shared ReadOnly Property LblPetitionInfo_P_H() As String
            Get
                Return ResourceManager.GetString("LblPetitionInfo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please note that the list may not be complete and that the information provided is for informational purposes and does not reflect an actual medical opinion..
        '''</summary>
        Friend Shared ReadOnly Property LblResultInfoo_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultInfoo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results.
        '''</summary>
        Friend Shared ReadOnly Property LblResults_P_H() As String
            Get
                Return ResourceManager.GetString("LblResults_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PATHOLOGIES SUFFERED.
        '''</summary>
        Friend Shared ReadOnly Property LblResultsTitle_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultsTitle_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose one answer in each row..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please choose the symptoms from the drop down list..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select an item to delete.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WELCOME BACK.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select all statements
        '''that apply to you..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add your symptoms to the list..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to    .
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symptoms you suffer from..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello!.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to License Terms..
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am overweight, or I am obese..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt1_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt1_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I smoke cigarettes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt2_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt2_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I have recently suffered an injury..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt3_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt3_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I have high cholesterol..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt4_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt4_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I have hypertension..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt5_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt5_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I have diabetes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt6_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt6_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I don&apos;t know..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Idk_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Idk_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_No_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_No_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Yes_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Yes_P_H", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
