'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Logic.Spanish", GetType(Spanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregado con éxito.
        '''</summary>
        Friend Shared ReadOnly Property AddWithSuccess() As String
            Get
                Return ResourceManager.GetString("AddWithSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property BtnAcceptPet_M_P() As String
            Get
                Return ResourceManager.GetString("BtnAcceptPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NUEVA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar Patología.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HPP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NUEVO SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddSympt_A_S() As String
            Get
                Return ResourceManager.GetString("BtnAddSympt_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administradores.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_H() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administradores.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Patient1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Patient1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CANCELAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnCancelPetition_P_HD() As String
            Get
                Return ResourceManager.GetString("BtnCancelPetition_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ELIMINAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnDelSympt_A_S() As String
            Get
                Return ResourceManager.GetString("BtnDelSympt_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a QUITAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnDropPathology_P_H() As String
            Get
                Return ResourceManager.GetString("BtnDropPathology_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FINALIZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnEnd_P_H() As String
            Get
                Return ResourceManager.GetString("BtnEnd_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CERRAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnExit_A_L() As String
            Get
                Return ResourceManager.GetString("BtnExit_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAQ.
        '''</summary>
        Friend Shared ReadOnly Property BtnFaq_A_H() As String
            Get
                Return ResourceManager.GetString("BtnFaq_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Página principal.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_H() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Página principal.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Página principal.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_M_H() As String
            Get
                Return ResourceManager.GetString("BtnHome_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_A_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_M_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_P_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar sesión.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_H() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar sesión.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Sesión.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogOut_M_H() As String
            Get
                Return ResourceManager.GetString("BtnLogOut_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médicos.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_H() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médicos.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnMod_A_S() As String
            Get
                Return ResourceManager.GetString("BtnMod_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICAR PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnModifyPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnModifyPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a EMPEZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Result_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Symptom1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Symptom1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REMOVER.
        '''</summary>
        Friend Shared ReadOnly Property BtnPin_A_R() As String
            Get
                Return ResourceManager.GetString("BtnPin_A_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Peticiones.
        '''</summary>
        Friend Shared ReadOnly Property BtnRequest_M_H() As String
            Get
                Return ResourceManager.GetString("BtnRequest_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ELIMINAR PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnRmPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnRmPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SOLICITAR CHAT.
        '''</summary>
        Friend Shared ReadOnly Property BtnSendChatP_P_H() As String
            Get
                Return ResourceManager.GetString("BtnSendChatP_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_H() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El chat ha finalizado!.
        '''</summary>
        Friend Shared ReadOnly Property ChatFinished_P_HC() As String
            Get
                Return ResourceManager.GetString("ChatFinished_P_HC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Validando campos.
        '''</summary>
        Friend Shared ReadOnly Property CheckingFields() As String
            Get
                Return ResourceManager.GetString("CheckingFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar Diagnóstico.
        '''</summary>
        Friend Shared ReadOnly Property ChkModDiag_M_C() As String
            Get
                Return ResourceManager.GetString("ChkModDiag_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar región.
        '''</summary>
        Friend Shared ReadOnly Property ChkReg_A_SA() As String
            Get
                Return ResourceManager.GetString("ChkReg_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar región.
        '''</summary>
        Friend Shared ReadOnly Property ChkRegAdd_A_SA() As String
            Get
                Return ResourceManager.GetString("ChkRegAdd_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cedula de identidad errónea.
        '''</summary>
        Friend Shared ReadOnly Property CiWrong() As String
            Get
                Return ResourceManager.GetString("CiWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Chat.
        '''</summary>
        Friend Shared ReadOnly Property CloseChat_M_C() As String
            Get
                Return ResourceManager.GetString("CloseChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Programa.
        '''</summary>
        Friend Shared ReadOnly Property CloseProgram_M_H() As String
            Get
                Return ResourceManager.GetString("CloseProgram_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Conexión fallida. Intentado recopilar datos....
        '''</summary>
        Friend Shared ReadOnly Property ConnectionFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Luego debe asociarle una o más patologias.
        '''</summary>
        Friend Shared ReadOnly Property CsvSymptomsMsg() As String
            Get
                Return ResourceManager.GetString("CsvSymptomsMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnóstico modificado con exito.
        '''</summary>
        Friend Shared ReadOnly Property DiagnosticModSuccess_M_C() As String
            Get
                Return ResourceManager.GetString("DiagnosticModSuccess_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  eliminado con éxito.
        '''</summary>
        Friend Shared ReadOnly Property EliminatedSuccessfull_A_R() As String
            Get
                Return ResourceManager.GetString("EliminatedSuccessfull_A_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Campos vacios o No selecciono patología asociada.
        '''</summary>
        Friend Shared ReadOnly Property EmptyFields_A_SA() As String
            Get
                Return ResourceManager.GetString("EmptyFields_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Está seguro que desea finalizar el chat ?.
        '''</summary>
        Friend Shared ReadOnly Property EndChat_M_C() As String
            Get
                Return ResourceManager.GetString("EndChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hay algún campo vacío..
        '''</summary>
        Friend Shared ReadOnly Property HayCamposVacios() As String
            Get
                Return ResourceManager.GetString("HayCamposVacios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agustín Yorel Acosta Bergonzoni..
        '''</summary>
        Friend Shared ReadOnly Property Label13() As String
            Get
                Return ResourceManager.GetString("Label13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Kevin Mathew Anadón Wappler..
        '''</summary>
        Friend Shared ReadOnly Property Label14() As String
            Get
                Return ResourceManager.GetString("Label14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mayza Daniela Ferreira Hernández..
        '''</summary>
        Friend Shared ReadOnly Property Label15() As String
            Get
                Return ResourceManager.GetString("Label15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ignacio Rodríguez Sosa..
        '''</summary>
        Friend Shared ReadOnly Property Label16() As String
            Get
                Return ResourceManager.GetString("Label16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usted está a punto de.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_A_R() As String
            Get
                Return ResourceManager.GetString("Lbl1_A_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Introducción.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_Intro_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl1_Intro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente.
        '''</summary>
        Friend Shared ReadOnly Property Lbl2_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl2_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property Lbl3_Symptom_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl3_Symptom_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resultados.
        '''</summary>
        Friend Shared ReadOnly Property Lbl4_Result_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl4_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property Lbl5_Chat_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl5_Chat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actual: .
        '''</summary>
        Friend Shared ReadOnly Property LblActual_A_SA() As String
            Get
                Return ResourceManager.GetString("LblActual_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar región.
        '''</summary>
        Friend Shared ReadOnly Property LblAddRegion_A_SA() As String
            Get
                Return ResourceManager.GetString("LblAddRegion_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERTAR NUEVO SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property LblAddSympt_A_SA() As String
            Get
                Return ResourceManager.GetString("LblAddSympt_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Asociación de patologías.
        '''</summary>
        Friend Shared ReadOnly Property LblAsocPath_A_SA() As String
            Get
                Return ResourceManager.GetString("LblAsocPath_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Asociación a la región.
        '''</summary>
        Friend Shared ReadOnly Property LblAsocReg_A_SA() As String
            Get
                Return ResourceManager.GetString("LblAsocReg_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ATENCIÓN.
        '''</summary>
        Friend Shared ReadOnly Property LblAttention_A_R() As String
            Get
                Return ResourceManager.GetString("LblAttention_A_R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese su usuario y contraseña 
        '''para autenticar y verificar sus credenciales.
        '''Este Software le permitirá tratar a sus Pacientes, brindándoles a estos, información para concluir un Telediagnóstico..
        '''</summary>
        Friend Shared ReadOnly Property LblBody_M_L() As String
            Get
                Return ResourceManager.GetString("LblBody_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Si usted lo desea puede consultar a un Médico..
        '''</summary>
        Friend Shared ReadOnly Property LblChat_P_H() As String
            Get
                Return ResourceManager.GetString("LblChat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CRITERIOS DE BÚSQUEDA.
        '''</summary>
        Friend Shared ReadOnly Property LblCrit_A_S() As String
            Get
                Return ResourceManager.GetString("LblCrit_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción.
        '''</summary>
        Friend Shared ReadOnly Property LblDescSympt_A_SA() As String
            Get
                Return ResourceManager.GetString("LblDescSympt_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar el síntoma:.
        '''</summary>
        Friend Shared ReadOnly Property LblElimBodySympt() As String
            Get
                Return ResourceManager.GetString("LblElimBodySympt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ELIMINAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property LblEliminarSympt() As String
            Get
                Return ResourceManager.GetString("LblEliminarSympt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Centro de Atención de Salud..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Campo Obligatorio [*].
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando conexión con la Base de Datos..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generando conexión con la Base de Datos..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_P_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_P_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Está a punto de realizar un chequeo médico breve (3 min), seguro y anónimo. Sus respuestas serán analizadas cuidadosamente y se le dirá las posibles causas de sus síntomas a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antes de utilizar esta herramienta, por favor, lea los términos del servicio. 
        '''
        '''Recuerde que:
        '''El chequeo tiene finalidad informativa y no sustituye la opinión de un médico.
        '''No usar en caso de emergencias. En caso de una emergencia de salud, llame a su número de emergencias locales inmediatamente. Sus datos están a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sistema de Gestión para Administradores..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administración de los Tratamientos.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este Sistema Médico fué creado con el propósito de cumplir las expecativas de un Programa Asistente, el cual lo guiará a usted a lo largo de su diagnóstico de patológias que pueda sufrir. Al ser este un Asistente, ustéd podrá conocer sus Patologías de la forma más ágil y simple.
        '''
        '''Que disfrute de nuestro servicio. Toque el botón debajo para empezar el diagnóstico.anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a V2.0.1 Beta..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo3_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo3_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a © Telediagnóstico Médico 2020. Derechos reservados.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo4_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FIN.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoEnd_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoEnd_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATOLOGÍA DIAGNOSTICADA.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoPathSuffered_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoPathSuffered_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PACIENTE.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoPatient_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoPatient_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SÍNTOMAS SUFRIDOS.
        '''</summary>
        Friend Shared ReadOnly Property LblInfoSympsSuffered_M_C() As String
            Get
                Return ResourceManager.GetString("LblInfoSympsSuffered_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese su usuario y contraseña 
        '''para autenticar y verificar sus credenciales.
        '''Este Software le permitirá gestionar al Personal, a los Pacientes, los Síntomas y sus Patologías asociadas..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_A_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese su Cédula de Identidad para autenticar y  verificar sus credenciales. Este Software le permitirá realizar Diagnósticos Primarios y en base de ellos decidirá si quiere iniciar una conversación con un Médico Especialista..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_P_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LISTADO DE SÍNTOMAS.
        '''</summary>
        Friend Shared ReadOnly Property LblListado_A_S() As String
            Get
                Return ResourceManager.GetString("LblListado_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LISTADO DE PETICIONES.
        '''</summary>
        Friend Shared ReadOnly Property LblListadoPet_M_P() As String
            Get
                Return ResourceManager.GetString("LblListadoPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medic.
        '''</summary>
        Friend Shared ReadOnly Property LblMedic_P_HC() As String
            Get
                Return ResourceManager.GetString("LblMedic_P_HC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GESTIÓN DE PATOLOGÍAS.
        '''</summary>
        Friend Shared ReadOnly Property LblMgmentPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblMgmentPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICAR DIAGNÓSTICO.
        '''</summary>
        Friend Shared ReadOnly Property LblModDiagnostic_M_C() As String
            Get
                Return ResourceManager.GetString("LblModDiagnostic_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblModDiagPath_M_C() As String
            Get
                Return ResourceManager.GetString("LblModDiagPath_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PETICIONES SOLICITADAS.
        '''</summary>
        Friend Shared ReadOnly Property LblPet_M_P() As String
            Get
                Return ResourceManager.GetString("LblPet_M_P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GENERANDO PETICIÓN.
        '''</summary>
        Friend Shared ReadOnly Property LblPetitionInfo_P_H() As String
            Get
                Return ResourceManager.GetString("LblPetitionInfo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está usted seguro de que quiere eliminar este síntoma?.
        '''</summary>
        Friend Shared ReadOnly Property LblPregunta_A_RSympt() As String
            Get
                Return ResourceManager.GetString("LblPregunta_A_RSympt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor, tenga en cuenta que la lista podría no ser completa y que la información proporcionada tiene una finalidad informativa y no se corresponde con una opinión médica real..
        '''</summary>
        Friend Shared ReadOnly Property LblResultInfoo_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultInfoo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LISTADO PATOLOGÍAS.
        '''</summary>
        Friend Shared ReadOnly Property LblResultPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblResultPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resultados.
        '''</summary>
        Friend Shared ReadOnly Property LblResults_P_H() As String
            Get
                Return ResourceManager.GetString("LblResults_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATOLOGÍAS SUFRIDAS.
        '''</summary>
        Friend Shared ReadOnly Property LblResultsTitle_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultsTitle_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No requiere de una valoración médica urgente..
        '''</summary>
        Friend Shared ReadOnly Property LblResultUrgent_M_C_NOTURGENTE() As String
            Get
                Return ResourceManager.GetString("LblResultUrgent_M_C_NOTURGENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Requiere de una valoración médica urgente..
        '''</summary>
        Friend Shared ReadOnly Property LblResultUrgent_M_C_URGENTE() As String
            Get
                Return ResourceManager.GetString("LblResultUrgent_M_C_URGENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CRITERIOS DE BÚSQUEDA.
        '''</summary>
        Friend Shared ReadOnly Property LblSearch_A_HP() As String
            Get
                Return ResourceManager.GetString("LblSearch_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Propietario.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Escoja una respuesta en cada fila..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor, escoja los síntomas desde la lista desplegable..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tasa de Mortalidad.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccione un ítem para eliminarlo.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Versión del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción de la Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desarrolladores del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre del Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle5_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle5_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción del Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle6_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle6_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle7_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle7_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LISTADO DE TRATAMIENTOS PARA LA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle8_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle8_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edad.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleAge_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleAge_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Última Conexión.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleConn_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleConn_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento o Credencial.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleCred_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleCred_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dirección de correo electrónico.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleEmail_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleEmail_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre Completo.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleName_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleName_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número telefónico.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleTel_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleTel_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSystemChat_M_C() As String
            Get
                Return ResourceManager.GetString("LblSystemChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ACERCA DEL SISTEMA.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICACIÓN DE LA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor, seleccione todas las afirmaciones 
        '''que se apliquen a usted..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Añada sus síntomas a la lista..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ACERCA DEL ADMINISTRADOR.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NUEVAMENTE..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ACERCA DEL MÉDICO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_M_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NUEVAMENTE.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas que padece..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¡Hola!.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Términos de licencia..
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En una conversación con el Médico:.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleNameMedic_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleNameMedic_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTittle1_M_L() As String
            Get
                Return ResourceManager.GetString("LblTittle1_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NUEVAMENTE..
        '''</summary>
        Friend Shared ReadOnly Property LblTittle2_M_L() As String
            Get
                Return ResourceManager.GetString("LblTittle2_M_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICACIÓN DEL SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property LblTittleAddSymp_A_SA() As String
            Get
                Return ResourceManager.GetString("LblTittleAddSymp_A_SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En una conversación con el Paciente:.
        '''</summary>
        Friend Shared ReadOnly Property LblTittleChat_M_C() As String
            Get
                Return ResourceManager.GetString("LblTittleChat_M_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GESTIÓN DE SÍNTOMAS.
        '''</summary>
        Friend Shared ReadOnly Property LblTittleSymps_A_S() As String
            Get
                Return ResourceManager.GetString("LblTittleSymps_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tengo sobrepeso, o estoy obeso..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt1_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt1_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fumo cigarrillos..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt2_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt2_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a He sufrido una lesión recientemente..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt3_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt3_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tengo el colesterol alto..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt4_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt4_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tengo hipertensión..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt5_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt5_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tengo diabétes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt6_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt6_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Está seguro que desea cerrar sesión ?.
        '''</summary>
        Friend Shared ReadOnly Property LogOut_M_H() As String
            Get
                Return ResourceManager.GetString("LogOut_M_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PETICIÓN GENERADA CORRECTAMENTE.
        '''</summary>
        Friend Shared ReadOnly Property MadeRequest_P_HD() As String
            Get
                Return ResourceManager.GetString("MadeRequest_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GENERANDO PETICIÓN.
        '''</summary>
        Friend Shared ReadOnly Property MakingRequest_P_HD() As String
            Get
                Return ResourceManager.GetString("MakingRequest_P_HD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patient.
        '''</summary>
        Friend Shared ReadOnly Property Medic__Chat__Label() As String
            Get
                Return ResourceManager.GetString("Medic. Chat. Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificado con éxito.
        '''</summary>
        Friend Shared ReadOnly Property ModifyWithSuccess() As String
            Get
                Return ResourceManager.GetString("ModifyWithSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Está seguro que desea salir ?.
        '''</summary>
        Friend Shared ReadOnly Property MsgExit() As String
            Get
                Return ResourceManager.GetString("MsgExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se encuentra habilitado..
        '''</summary>
        Friend Shared ReadOnly Property NotEnable() As String
            Get
                Return ResourceManager.GetString("NotEnable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No lo sé..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Idk_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Idk_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_No_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_No_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Si..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Yes_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Yes_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medicamento.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnMedicine_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnMedicine_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Quirúrgico.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnQuir_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnQuir_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inicio de sesión exitoso..
        '''</summary>
        Friend Shared ReadOnly Property SuccessLogin() As String
            Get
                Return ResourceManager.GetString("SuccessLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Realizar busqueda por patología.
        '''</summary>
        Friend Shared ReadOnly Property TxtSearchPath_A_HP() As String
            Get
                Return ResourceManager.GetString("TxtSearchPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Realizar búsqueda por síntoma.
        '''</summary>
        Friend Shared ReadOnly Property TxtSympt_A_S() As String
            Get
                Return ResourceManager.GetString("TxtSympt_A_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User .
        '''</summary>
        Friend Shared ReadOnly Property UserInfoHome_A_H() As String
            Get
                Return ResourceManager.GetString("UserInfoHome_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a conectado a las .
        '''</summary>
        Friend Shared ReadOnly Property UserInfoHomeCon_A_H() As String
            Get
                Return ResourceManager.GetString("UserInfoHomeCon_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario y/o Contraseña erroneos..
        '''</summary>
        Friend Shared ReadOnly Property UserOrPassWrong() As String
            Get
                Return ResourceManager.GetString("UserOrPassWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PIN incorrecto.
        '''</summary>
        Friend Shared ReadOnly Property WrongPin_A_R() As String
            Get
                Return ResourceManager.GetString("WrongPin_A_R", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
