'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Logic.Spanish", GetType(Spanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Patient1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Patient1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QUITAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnDropPathology_P_H() As String
            Get
                Return ResourceManager.GetString("BtnDropPathology_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FINALIZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnEnd_P_H() As String
            Get
                Return ResourceManager.GetString("BtnEnd_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_P_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMPEZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Result_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Symptom1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Symptom1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOLICITAR CHAT.
        '''</summary>
        Friend Shared ReadOnly Property BtnSendChatP_P_H() As String
            Get
                Return ResourceManager.GetString("BtnSendChatP_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introducción.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_Intro_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl1_Intro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paciente.
        '''</summary>
        Friend Shared ReadOnly Property Lbl2_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl2_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property Lbl3_Symptom_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl3_Symptom_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultados.
        '''</summary>
        Friend Shared ReadOnly Property Lbl4_Result_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl4_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat.
        '''</summary>
        Friend Shared ReadOnly Property Lbl5_Chat_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl5_Chat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En las próximas versiones de nuestro sistema, podrá consultar con un Médico..
        '''</summary>
        Friend Shared ReadOnly Property LblChat_P_H() As String
            Get
                Return ResourceManager.GetString("LblChat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generando conexión con la Base de Datos..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_P_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_P_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Está a punto de realizar un chequeo médico breve (3 min), seguro y anónimo. Sus respuestas serán analizadas cuidadosamente y se le dirá las posibles causas de sus síntomas a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antes de utilizar esta herramienta, por favor, lea los términos del servicio. 
        '''
        '''Recuerde que:
        '''El chequeo tiene finalidad informativa y no sustituye la opinión de un médico.
        '''No usar en caso de emergencias. En caso de una emergencia de salud, llame a su número de emergencias locales inmediatamente. Sus datos están a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este Sistema Médico fué creado con el propósito de cumplir las expecativas de un Programa Asistente, el cual lo guiará a usted a lo largo de su diagnóstico de patológias que pueda sufrir. Al ser este un Asistente, ustéd podrá conocer sus Patologías de la forma más ágil y simple.
        '''
        '''Que disfrute de nuestro servicio. Toque el botón debajo para empezar el diagnóstico.anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese su Cédula de Identidad para autenticar y  verificar sus credenciales. Este Software le permitirá realizar Diagnósticos Primarios y en base de ellos decidirá si quiere iniciar una conversación con un Médico Especialista..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_P_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GENERANDO PETICIÓN.
        '''</summary>
        Friend Shared ReadOnly Property LblPetitionInfo_P_H() As String
            Get
                Return ResourceManager.GetString("LblPetitionInfo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, tenga en cuenta que la lista podría no ser completa y que la información proporcionada tiene una finalidad informativa y no se corresponde con una opinión médica real..
        '''</summary>
        Friend Shared ReadOnly Property LblResultInfoo_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultInfoo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultados.
        '''</summary>
        Friend Shared ReadOnly Property LblResults_P_H() As String
            Get
                Return ResourceManager.GetString("LblResults_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PATOLOGÍAS SUFRIDAS.
        '''</summary>
        Friend Shared ReadOnly Property LblResultsTitle_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultsTitle_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escoja una respuesta en cada fila..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, escoja los síntomas desde la lista desplegable..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione un ítem para eliminarlo.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, seleccione todas las afirmaciones 
        '''que se apliquen a usted..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añada sus síntomas a la lista..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NUEVAMENTE.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas que padece..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Hola!.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Términos de licencia..
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo sobrepeso, o estoy obeso..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt1_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt1_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fumo cigarrillos..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt2_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt2_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to He sufrido una lesión recientemente..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt3_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt3_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo el colesterol alto..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt4_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt4_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo hipertensión..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt5_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt5_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo diabétes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt6_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt6_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No lo sé..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Idk_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Idk_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_No_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_No_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Yes_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Yes_P_H", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
