'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Logic.Spanish", GetType(Spanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NUEVA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Patología.
        '''</summary>
        Friend Shared ReadOnly Property BtnAddPath_A_HPP() As String
            Get
                Return ResourceManager.GetString("BtnAddPath_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administradores.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_H() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administradores.
        '''</summary>
        Friend Shared ReadOnly Property BtnAdmins_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnAdmins_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATRAS.
        '''</summary>
        Friend Shared ReadOnly Property BtnBack_Patient1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnBack_Patient1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QUITAR SÍNTOMA.
        '''</summary>
        Friend Shared ReadOnly Property BtnDropPathology_P_H() As String
            Get
                Return ResourceManager.GetString("BtnDropPathology_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FINALIZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnEnd_P_H() As String
            Get
                Return ResourceManager.GetString("BtnEnd_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CERRAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnExit_A_L() As String
            Get
                Return ResourceManager.GetString("BtnExit_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Página principal.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_H() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Página principal.
        '''</summary>
        Friend Shared ReadOnly Property BtnHome_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnHome_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_A_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INICIAR SESIÓN.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogin_P_L() As String
            Get
                Return ResourceManager.GetString("BtnLogin_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar sesión.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_H() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar sesión.
        '''</summary>
        Friend Shared ReadOnly Property BtnLogout_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnLogout_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Médicos.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_H() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Médicos.
        '''</summary>
        Friend Shared ReadOnly Property BtnMedics_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnMedics_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MODIFICAR PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnModifyPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnModifyPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMPEZAR.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Result_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIGUIENTE.
        '''</summary>
        Friend Shared ReadOnly Property BtnNext_Symptom1_P_H() As String
            Get
                Return ResourceManager.GetString("BtnNext_Symptom1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patologías.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patologías.
        '''</summary>
        Friend Shared ReadOnly Property BtnPathologies_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPathologies_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_H() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property BtnPatients_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnPatients_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ELIMINAR PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property BtnRmPath_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnRmPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOLICITAR CHAT.
        '''</summary>
        Friend Shared ReadOnly Property BtnSendChatP_P_H() As String
            Get
                Return ResourceManager.GetString("BtnSendChatP_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_H() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property BtnSymp_A_HP() As String
            Get
                Return ResourceManager.GetString("BtnSymp_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introducción.
        '''</summary>
        Friend Shared ReadOnly Property Lbl1_Intro_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl1_Intro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paciente.
        '''</summary>
        Friend Shared ReadOnly Property Lbl2_Patient_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl2_Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property Lbl3_Symptom_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl3_Symptom_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultados.
        '''</summary>
        Friend Shared ReadOnly Property Lbl4_Result_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl4_Result_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat.
        '''</summary>
        Friend Shared ReadOnly Property Lbl5_Chat_P_H() As String
            Get
                Return ResourceManager.GetString("Lbl5_Chat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En las próximas versiones de nuestro sistema, podrá consultar con un Médico..
        '''</summary>
        Friend Shared ReadOnly Property LblChat_P_H() As String
            Get
                Return ResourceManager.GetString("LblChat_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campo Obligatorio [*].
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generando conexión con la Base de Datos..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_A_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_A_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generando conexión con la Base de Datos..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1_P_SS() As String
            Get
                Return ResourceManager.GetString("LblInfo1_P_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Está a punto de realizar un chequeo médico breve (3 min), seguro y anónimo. Sus respuestas serán analizadas cuidadosamente y se le dirá las posibles causas de sus síntomas a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antes de utilizar esta herramienta, por favor, lea los términos del servicio. 
        '''
        '''Recuerde que:
        '''El chequeo tiene finalidad informativa y no sustituye la opinión de un médico.
        '''No usar en caso de emergencias. En caso de una emergencia de salud, llame a su número de emergencias locales inmediatamente. Sus datos están a salvo. La información que usted proporcione es anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo1Intro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo1Intro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sistema de Gestión para Administradores..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administración de los Tratamientos.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblInfo2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este Sistema Médico fué creado con el propósito de cumplir las expecativas de un Programa Asistente, el cual lo guiará a usted a lo largo de su diagnóstico de patológias que pueda sufrir. Al ser este un Asistente, ustéd podrá conocer sus Patologías de la forma más ágil y simple.
        '''
        '''Que disfrute de nuestro servicio. Toque el botón debajo para empezar el diagnóstico.anónima y no será compartida con nadie..
        '''</summary>
        Friend Shared ReadOnly Property LblInfo2Intro1_P_H() As String
            Get
                Return ResourceManager.GetString("LblInfo2Intro1_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to © Telediagnóstico Médico 2020. Derechos reservados.
        '''</summary>
        Friend Shared ReadOnly Property LblInfo4_A_H() As String
            Get
                Return ResourceManager.GetString("LblInfo4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese su usuario y contraseña 
        '''para autenticar y verificar sus credenciales.
        '''Este Software le permitirá gestionar al Personal, a los Pacientes, los Síntomas y sus Patologías asociadas..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_A_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingrese su Cédula de Identidad para autenticar y  verificar sus credenciales. Este Software le permitirá realizar Diagnósticos Primarios y en base de ellos decidirá si quiere iniciar una conversación con un Médico Especialista..
        '''</summary>
        Friend Shared ReadOnly Property LblInfoText_P_L() As String
            Get
                Return ResourceManager.GetString("LblInfoText_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GESTIÓN DE PATOLOGÍAS.
        '''</summary>
        Friend Shared ReadOnly Property LblMgmentPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblMgmentPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GENERANDO PETICIÓN.
        '''</summary>
        Friend Shared ReadOnly Property LblPetitionInfo_P_H() As String
            Get
                Return ResourceManager.GetString("LblPetitionInfo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, tenga en cuenta que la lista podría no ser completa y que la información proporcionada tiene una finalidad informativa y no se corresponde con una opinión médica real..
        '''</summary>
        Friend Shared ReadOnly Property LblResultInfoo_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultInfoo_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LISTADO PATOLOGÍAS.
        '''</summary>
        Friend Shared ReadOnly Property LblResultPath_A_HP() As String
            Get
                Return ResourceManager.GetString("LblResultPath_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultados.
        '''</summary>
        Friend Shared ReadOnly Property LblResults_P_H() As String
            Get
                Return ResourceManager.GetString("LblResults_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PATOLOGÍAS SUFRIDAS.
        '''</summary>
        Friend Shared ReadOnly Property LblResultsTitle_P_H() As String
            Get
                Return ResourceManager.GetString("LblResultsTitle_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CRITERIOS DE BÚSQUEDA.
        '''</summary>
        Friend Shared ReadOnly Property LblSearch_A_HP() As String
            Get
                Return ResourceManager.GetString("LblSearch_A_HP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Propietario.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escoja una respuesta en cada fila..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, escoja los síntomas desde la lista desplegable..
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tasa de Mortalidad.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione un ítem para eliminarlo.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Versión del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción de la Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle3_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle3_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desarrolladores del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Patología.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle4_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle4_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre del Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle5_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle5_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción del Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle6_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle6_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Tratamiento.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle7_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle7_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LISTADO DE TRATAMIENTOS PARA LA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitle8_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblSubTitle8_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edad.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleAge_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleAge_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Última Conexión.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleConn_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleConn_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documento o Credencial.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleCred_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleCred_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección de correo electrónico.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleEmail_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleEmail_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre Completo.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleName_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleName_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número telefónico.
        '''</summary>
        Friend Shared ReadOnly Property LblSubTitleTel_A_H() As String
            Get
                Return ResourceManager.GetString("LblSubTitleTel_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ACERCA DEL SISTEMA.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MODIFICACIÓN DE LA PATOLOGÍA.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_HPP() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUSTO EN VERLO.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle1_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, seleccione todas las afirmaciones 
        '''que se apliquen a usted..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Patient_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Patient_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añada sus síntomas a la lista..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle1Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle1Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ACERCA DEL ADMINISTRADOR.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NUEVAMENTE..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_A_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_A_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NUEVAMENTE.
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2_P_L() As String
            Get
                Return ResourceManager.GetString("LblTitle2_P_L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Síntomas que padece..
        '''</summary>
        Friend Shared ReadOnly Property LblTitle2Symp_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitle2Symp_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Hola!.
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Términos de licencia..
        '''</summary>
        Friend Shared ReadOnly Property LblTitleIntro2_P_H() As String
            Get
                Return ResourceManager.GetString("LblTitleIntro2_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo sobrepeso, o estoy obeso..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt1_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt1_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fumo cigarrillos..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt2_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt2_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to He sufrido una lesión recientemente..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt3_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt3_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo el colesterol alto..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt4_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt4_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo hipertensión..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt5_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt5_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tengo diabétes..
        '''</summary>
        Friend Shared ReadOnly Property LblTxt6_Info_P_H() As String
            Get
                Return ResourceManager.GetString("LblTxt6_Info_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No lo sé..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Idk_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Idk_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_No_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_No_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si..
        '''</summary>
        Friend Shared ReadOnly Property Rbtn1_Yes_P_H() As String
            Get
                Return ResourceManager.GetString("Rbtn1_Yes_P_H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medicamento.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnMedicine_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnMedicine_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quirúrgico.
        '''</summary>
        Friend Shared ReadOnly Property RdbtnQuir_A_HPP() As String
            Get
                Return ResourceManager.GetString("RdbtnQuir_A_HPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Realizar busqueda por patología.
        '''</summary>
        Friend Shared ReadOnly Property TxtSearchPath_A_HP() As String
            Get
                Return ResourceManager.GetString("TxtSearchPath_A_HP", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
